<?php

$host = "localhost";
$dbname = "DockMeet";
$username = "root";
$password = "";

$mysqli = new mysqli($host, $username, $password, $dbname);

if($mysqli->connect_errno){
    die("Connection error: " . $mysqli->connect_error);
}

$practices = array(
    array('userID' => 1, 'practiceName' => 'Harmony Wellness Center', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 1', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'practiceType' => 'Family'),
    array('userID' => 2, 'practiceName' => 'Serenity Health Clinic', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 2', 'zipcode' => 12345, 'city' => 'Fullerton', 'country' => 'US', 'practiceType' => 'Pediatric'),
    array('userID' => 3, 'practiceName' => 'Vitality Healing Studio', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 3', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'practiceType' => 'Orthopedic'),
    array('userID' => 4, 'practiceName' => 'Tranquil Mind and Body Institute', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 4', 'zipcode' => 12345, 'city' => 'Fullerton', 'country' => 'US', 'practiceType' => 'Dermatology'),
    array('userID' => 5, 'practiceName' => 'Renewal Therapeutic Services', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 5', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'practiceType' => 'Gastrology'),
    array('userID' => 6, 'practiceName' => 'Inner Balance Holistic Practice', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 6', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'practiceType' => 'Urology'),
    array('userID' => 7, 'practiceName' => 'Radiant Life Wellness Clinic', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 7', 'zipcode' => 54321, 'city' => 'Glendale', 'country' => 'US', 'practiceType' => 'Surgery'),
    array('userID' => 8, 'practiceName' => 'Empowerment Pathways Center', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 8', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'practiceType' => 'Physical Therapy'),
    array('userID' => 9, 'practiceName' => 'Healing Haven Wellness Studio', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 9', 'zipcode' => 54321, 'city' => 'Glendale', 'country' => 'US', 'practiceType' => 'Neurology'),
    array('userID' => 10, 'practiceName' => 'Mindful Living Practice', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 10', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'practiceType' => 'Endocrinology'),


);

$providers = array(
    array('userID' => 11, 'providerName' => 'Justin Gonzales', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 11', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'providerType' => 'Family'),
    array('userID' => 12, 'providerName' => 'Ismail Hasan', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 12', 'zipcode' => 12345, 'city' => 'Fullerton', 'country' => 'US', 'providerType' => 'General Practitioner'),
    array('userID' => 13, 'providerName' => 'Olivia Foster', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 13', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'providerType' => 'Cardiologist'),
    array('userID' => 14, 'providerName' => 'Lucas Martinez', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 14', 'zipcode' => 12345, 'city' => 'Fullerton', 'country' => 'US', 'providerType' => 'Dermatologist'),
    array('userID' => 15, 'providerName' => 'Emily Wilson', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 15', 'zipcode' => 12345, 'city' => 'Glendale', 'country' => 'US', 'providerType' => 'Urologist'),
    array('userID' => 16, 'providerName' => 'Benjamin Evans', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 16', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'providerType' => 'Radiologist'),
    array('userID' => 17, 'providerName' => 'Isabella Harris', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 17', 'zipcode' => 54321, 'city' => 'Glendale', 'country' => 'US', 'providerType' => 'Nurse Practitioner'),
    array('userID' => 18, 'providerName' => 'Mason Rivera', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 18', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'providerType' => 'Chiropractor'),
    array('userID' => 19, 'providerName' => 'Ava Davis', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 19', 'zipcode' => 54321, 'city' => 'Glendale', 'country' => 'US', 'providerType' => 'Dietitian'),
    array('userID' => 20, 'providerName' => 'Noah Miller', 'bio' => 'A renowned medical practice committed to providing comprehensive and compassionate healthcare. Our dedicated team of highly skilled physicians and specialists offers personalized treatment plans, advanced diagnostics, and state-of-the-art medical interventions. With a focus on patient well-being, we strive to deliver exceptional care, fostering healing and promoting long-lasting health for individuals and families in our community.', 'streetAddress' => 'Address 20', 'zipcode' => 54321, 'city' => 'Fullerton', 'country' => 'US', 'providerType' => 'Surgeon'),


);




foreach($practices as $practice) {
    $sql = "INSERT INTO practices (userID, practiceName, bio, streetAddress, zipcode, city, country, practiceType)
            VALUES ({$practice['userID']}, '{$practice['practiceName']}', '{$practice['bio']}', '{$practice['streetAddress']}', {$practice['zipcode']}, '{$practice['city']}', '{$practice['country']}', '{$practice['practiceType']}')";
    $mysqli->query($sql);
}


foreach($providers as $provider) {
    $sql = "INSERT INTO providers (userID, providerName, bio, streetAddress, zipcode, city, country, providerType)
            VALUES ({$provider['userID']}, '{$provider['providerName']}', '{$provider['bio']}', '{$provider['streetAddress']}', {$provider['zipcode']}, '{$provider['city']}', '{$provider['country']}', '{$provider['providerType']}')";
    $mysqli->query($sql);
}

$mysqli->close();

echo "Mock data inserted successfully!";
?>